### ISSUE TITLE
Linked example site has 404 error

### ISSUE THREAD

**Issue by biblenerd** [otseng/simple-unique-bible-viewer#2]
When visiting https://simple-unique-bible-viewer.vercel.app it shows a 404 error:

```
404: NOT_FOUND
Code: DEPLOYMENT_NOT_FOUND
ID: cle1::fp866-1678722344562-6e58c8cf82d1
```

**Comment by otseng** [comment]
This is no longer used.  Where is this referenced so I can delete that?

Refer to [FAQ](https://github.com/otseng/simple-unique-bible-viewer/wiki/FAQ) on how to access it.

**Comment by biblenerd** [comment]
Thanks, it looks cool!
